### ISSUE TITLE
Help Promote DanceJS - Oct 4th

### ISSUE THREAD

**Issue by bcoe** [emilyrose/ravejs#16]
Tickets are on sale now! Thanks to @mikeal for letting us use his fee-free account.

You can buy the tickets at http://dancejs.io

https://twitter.com/benjamincoe/status/510108321257234432

Could people retweet me, or tweet a link to the site themselves.

We've only got a few weeks to sell 200 tickets, any other ideas for promotion?

**Comment by TheAlphaNerd** [comment]
OH HAI
